<?php

namespace Atrapalo\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
    public function byName($aName)
    {
        $qb = $this->createQueryBuilder('p');
        $qb
            ->where('p.name = :name')
        ;

        $query = $qb->getQuery();

        $query->setParameter('name', $aName);

        return $query->getResult();
    }
}
